name: compumatrix
description: "A production-ready Flutter project with Clean Architecture."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  dio: ^5.4.1
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.7
  intl: any
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true # For localization

  # assets:
  #   - assets/images/
